package ru.gothmog.command;

public enum CommandName {
    AUTHORIZATION, REGISTRATION, ADD_NEW_PRODUCT, ADD_NEW_CATEGORY_PRODUCT, ADD_TO_BLACKLIST, REMOVE_FROM_BLACKLIST, ORDER, EDIT_PRODUCT,
    REMOVE_PRODUCT, CANCEL_ORDER, LOG_OUT, NO_SUCH_COMMAND, CHOOSE_LANGUAGE, SHOW_CORRECT_CLIENTS, SHOW_BLACKLIST, SHOW_INFORMATION_ABOUT_PRODUCT,
    GO_ADD_PRODUCT, GO_EDIT_PRODUCT, SHOW_ORDERS, GO_TO_ADMIN_PAGE;
}
